apiVersion: v1
kind: LimitRange
metadata:
  name: kube-system-limit-range
  namespace: kube-system
spec:
  limits:
  - default:
      memory: 128Mi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 200m
    type: Container